import { ProgressLayOut } from "@/components";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Poppins } from "next/font/google";
import MyState from "@/context/MyState";
import { Metadata } from "next";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: {
    default: "social media app",
    template: "social media app - %s",
  },
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={poppins.className}>
      <ProgressLayOut>
        <MyState>{children}</MyState>
        <ToastContainer />
      </ProgressLayOut>
    </body>
  </html>
);

export default RootLayout;
